service: analysis-api

provider:
    name: aws
    runtime: nodejs18.x

functions:
    analyze:
        handler: src/handler.analyze
        events:
            - httpApi:
                path: /analyze
                method: post

package:
    individually: true

plugins:
    - serverless-webpack
    - serverless-offline

custom:
    webpack:
        webpackConfig: webpack.config.js
        includeModules: true
        packager: npm
    serverless-offline:
        httpPort: 4001
        lambdaPort: 4002
