service: analysis-api

frameworkVersion: '3'

provider:
    name: aws
    runtime: nodejs18.x
    region: us-east-1

functions:
    analyze:
        handler: src/handler.analyze
        events:
            - httpApi:
                path: /analyze
                method: post

package:
    individually: true

plugins:
    - serverless-webpack
    - serverless-offline

custom:
    webpack:
        webpackConfig: webpack.config.js
        packager: npm
        includeModules: true
    serverless-offline:
        httpPort: 4001
        lambdaPort: 4002
    stages:
        - dev
        - prod
